/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('placeholderdata').del()
  // Inserting garbage placeholder data generated via chatGPT
  await knex('placeholderdata').insert([
    {
      id: 1,
      Country: 'Japan',
      City: 'Tokyo',
      Attraction: 'Shibuya Crossing',
      Cuisine: 'Sushi',
      Climate: 'Temperate',
    },
    {
      id: 2,
      Country: 'Japan',
      City: 'Kyoto',
      Attraction: 'Fushimi Inari Shrine',
      Cuisine: 'Tempura',
      Climate: 'Temperate',
    },
    {
      id: 3,
      Country: 'France',
      City: 'Paris',
      Attraction: 'Eiffel Tower',
      Cuisine: 'Croissant',
      Climate: 'Mild',
    },
    {
      id: 4,
      Country: 'France',
      City: 'Nice',
      Attraction: 'Promenade des Anglais',
      Cuisine: 'Bouillabaisse',
      Climate: 'Mediterranean',
    },
    {
      id: 5,
      Country: 'USA',
      City: 'New York',
      Attraction: 'Statue of Liberty',
      Cuisine: 'Hot Dog',
      Climate: 'Seasonal',
    },
    {
      id: 6,
      Country: 'USA',
      City: 'Los Angeles',
      Attraction: 'Hollywood Sign',
      Cuisine: 'Tacos',
      Climate: 'Mediterranean',
    },
    {
      id: 7,
      Country: 'Italy',
      City: 'Rome',
      Attraction: 'Colosseum',
      Cuisine: 'Pasta',
      Climate: 'Mediterranean',
    },
    {
      id: 8,
      Country: 'Italy',
      City: 'Venice',
      Attraction: 'Grand Canal',
      Cuisine: 'Seafood',
      Climate: 'Mediterranean',
    },
    {
      id: 9,
      Country: 'Brazil',
      City: 'Rio de Janeiro',
      Attraction: 'Christ the Redeemer',
      Cuisine: 'Feijoada',
      Climate: 'Tropical',
    },
    {
      id: 10,
      Country: 'Brazil',
      City: 'Sao Paulo',
      Attraction: 'Ibirapuera Park',
      Cuisine: 'Coxinha',
      Climate: 'Tropical',
    },
    {
      id: 11,
      Country: 'Australia',
      City: 'Sydney',
      Attraction: 'Sydney Opera House',
      Cuisine: 'Barbecue',
      Climate: 'Subtropical',
    },
    {
      id: 12,
      Country: 'Australia',
      City: 'Melbourne',
      Attraction: 'Great Ocean Road',
      Cuisine: 'Meat Pie',
      Climate: 'Temperate',
    },
    {
      id: 13,
      Country: 'India',
      City: 'New Delhi',
      Attraction: 'Taj Mahal',
      Cuisine: 'Chole bhature',
      Climate: 'Varied',
    },
    {
      id: 14,
      Country: 'India',
      City: 'Mumbai',
      Attraction: 'Gateway of India',
      Cuisine: 'Vada Pav',
      Climate: 'Tropical',
    },
    {
      id: 15,
      Country: 'Egypt',
      City: 'Cairo',
      Attraction: 'Pyramids of Giza',
      Cuisine: 'Koshari',
      Climate: 'Arid',
    },
    {
      id: 16,
      Country: 'Egypt',
      City: 'Luxor',
      Attraction: 'Valley of the Kings',
      Cuisine: 'Ful Medames',
      Climate: 'Arid',
    },
    {
      id: 17,
      Country: 'Spain',
      City: 'Barcelona',
      Attraction: 'Sagrada Familia',
      Cuisine: 'Tapas',
      Climate: 'Mediterranean',
    },
    {
      id: 18,
      Country: 'Spain',
      City: 'Madrid',
      Attraction: 'Royal Palace',
      Cuisine: 'Paella',
      Climate: 'Continental',
    },
    {
      id: 19,
      Country: 'Canada',
      City: 'Toronto',
      Attraction: 'CN Tower',
      Cuisine: 'Poutine',
      Climate: 'Seasonal',
    },
    {
      id: 20,
      Country: 'Canada',
      City: 'Vancouver',
      Attraction: 'Stanley Park',
      Cuisine: 'Sushi',
      Climate: 'Oceanic',
    },
  ])
}
